services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "npm run build && npm start"

networks:
  default:
    driver: bridge